<!-- BEGIN:pinksundew-sync -->
// AUTO-GENERATED BY PINK SUNDEW - DO NOT EDIT THIS BLOCK
<<<<<<< HEAD
// Last synced: 2026-04-17T23:19:32.286404+00:00
=======
// Last synced: 2026-04-17T17:06:01.752397+00:00
>>>>>>> e9e236d04dfc59c846464e5325d6d911a4f26cf1
// Project: Pink Sundew

You are an advanced software engineer.

### Repo Architecture
Repo should be designed with domain driven and type-first design principles
Question everything I tell you to do. If a task seems incorrect or inoptimal, tell me.
<<<<<<< HEAD
Never commit any sensitive information, add to gitignore
=======
>>>>>>> e9e236d04dfc59c846464e5325d6d911a4f26cf1

### Task Workflow
If I tell you to look at my tasks or check them out, it means to pull them from the board and start working on them. Work on all tasks unless specified not to
Only work on in-progress or todo tasks.
Always mark tickets you work on as in progress. When finished, mark them for review, not as completed.
Always check replies for more information.
Signal tickets you are working on as Agent Working

### UI
Keep new UI consistent in design and coloring (Primary color - #f9a8d4)
Make sure you never use a default browser pop-up. Every pop-up should be custom and fit with the established UI.

### MCP Server
<<<<<<< HEAD
If you make any changes to the MCP server don't bump the version, our github actions do that
=======
If you make any changes to the MCP server that need to be pushed to npm, make sure you bump the version number
>>>>>>> e9e236d04dfc59c846464e5325d6d911a4f26cf1
<!-- END:pinksundew-sync -->
