/**
 * Pink Sundew MCP Server - Global Instruction Sync
 *
 * Synchronizes agent instructions from the cloud API to local workspace files.
 * This ensures that IDE-native instruction files (.cursorrules, CLAUDE.md, etc.)
 * are always up-to-date, avoiding context dilution from MCP resource injection.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { getAllowedProjectIds, isProjectScopingEnabled } from './project-scope.js'
import { getProjectAgentControls, getInstructionFilesForProject } from './resources.js'
import { bridgeFetch } from './supabase.js'
import type { AgentInstructionSet } from './types.js'

const GENERATED_HEADER = `// AUTO-GENERATED BY PINK SUNDEW MCP - DO NOT EDIT MANUALLY
// Last synced: {{TIMESTAMP}}
// Project: {{PROJECT_NAME}}

`

/**
 * Supported IDE instruction file targets.
 * Each IDE reads instructions from a specific file in the workspace root.
 */
const IDE_TARGETS = {
  cursor: '.cursorrules',
  claudeCode: 'CLAUDE.md',
  codex: 'codex.md',
  antigravity: 'antigravity.md',
  vscode: '.github/copilot-instructions.md',
} as const

type IdeTarget = keyof typeof IDE_TARGETS

export type SyncOptions = {
  /** Which IDE targets to sync. Defaults to all. */
  targets?: IdeTarget[]
  /** Workspace root directory. Defaults to process.cwd(). */
  workspaceRoot?: string
  /** Whether to log sync activity. Defaults to true. */
  verbose?: boolean
}

export type SyncResult = {
  success: boolean
  projectId: string | null
  projectName: string | null
  filesWritten: string[]
  instructionCount: number
  error?: string
}

/**
 * Fetches the active global instruction sets for a project.
 */
async function fetchActiveInstructions(projectId: string): Promise<{
  projectName: string
  instructions: AgentInstructionSet[]
}> {
  // Get agent controls to find active instruction set IDs
  const controls = await getProjectAgentControls(projectId)
  
  // Fetch the board state which includes instructions
  const boardState = await bridgeFetch<{
    project: { id: string; name: string } | null
    instructions: AgentInstructionSet[]
  }>(`/board/${projectId}`)

  // Filter to only global scope instructions that are active
  const activeInstructions = (boardState.instructions || []).filter(
    (instruction) => instruction.scope === 'global' && instruction.is_active !== false
  )

  // Fetch full content for each instruction set's files
  const allFileIds = activeInstructions.flatMap((set) =>
    set.files
      .filter((file) => file.file_name.toLowerCase().endsWith('.md'))
      .map((file) => file.id)
  )

  if (allFileIds.length > 0) {
    const filesWithContent = await getInstructionFilesForProject(projectId, allFileIds)
    const contentMap = new Map(filesWithContent.map((f) => [f.id, f.content]))

    // Merge content into instruction sets
    for (const instruction of activeInstructions) {
      for (const file of instruction.files) {
        const content = contentMap.get(file.id)
        if (content !== undefined) {
          file.content = content
        }
      }
    }
  }

  return {
    projectName: boardState.project?.name ?? 'Unknown Project',
    instructions: activeInstructions,
  }
}

/**
 * Concatenates all instruction content into a single formatted string.
 */
function buildCombinedContent(
  instructions: AgentInstructionSet[],
  projectName: string
): string {
  const timestamp = new Date().toISOString()
  const header = GENERATED_HEADER
    .replace('{{TIMESTAMP}}', timestamp)
    .replace('{{PROJECT_NAME}}', projectName)

  const sections: string[] = []

  for (const instruction of instructions) {
    // Sort files by name for consistent ordering
    const sortedFiles = [...instruction.files].sort((a, b) =>
      a.file_name.localeCompare(b.file_name)
    )

    for (const file of sortedFiles) {
      if (typeof file.content !== 'string' || !file.content.trim()) {
        continue
      }

      // Add section header for multi-file instruction sets
      if (instruction.files.length > 1 || instructions.length > 1) {
        sections.push(`<!-- ${instruction.name}: ${file.file_name} -->\n`)
      }
      sections.push(file.content.trim())
      sections.push('\n')
    }
  }

  if (sections.length === 0) {
    return header + '<!-- No active global instructions configured -->\n'
  }

  return header + sections.join('\n')
}

/**
 * Writes content to a file, creating parent directories if needed.
 */
function writeInstructionFile(filePath: string, content: string): void {
  const dir = path.dirname(filePath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }
  fs.writeFileSync(filePath, content, 'utf-8')
}

/**
 * Synchronizes global instructions from the cloud to local workspace files.
 * Writes to .cursorrules, CLAUDE.md, codex.md, antigravity.md, and .github/copilot-instructions.md.
 */
export async function syncGlobalInstructions(options: SyncOptions = {}): Promise<SyncResult> {
  const {
    targets = ['cursor', 'claudeCode', 'codex', 'antigravity', 'vscode'],
    workspaceRoot = process.cwd(),
    verbose = true,
  } = options

  const log = verbose ? console.error.bind(console) : () => {}

  // Get the first configured project ID
  if (!isProjectScopingEnabled()) {
    const error = 'No AGENTPLANNER_PROJECT_IDS configured. Cannot sync instructions.'
    log(`[sync] ${error}`)
    return {
      success: false,
      projectId: null,
      projectName: null,
      filesWritten: [],
      instructionCount: 0,
      error,
    }
  }

  const projectId = getAllowedProjectIds()[0]
  log(`[sync] Syncing global instructions for project: ${projectId}`)

  try {
    // Fetch active instructions from the API
    const { projectName, instructions } = await fetchActiveInstructions(projectId)
    log(`[sync] Found ${instructions.length} active global instruction set(s) for "${projectName}"`)

    // Build combined content
    const content = buildCombinedContent(instructions, projectName)

    // Write to each target file
    const filesWritten: string[] = []
    for (const target of targets) {
      const relativePath = IDE_TARGETS[target]
      const fullPath = path.join(workspaceRoot, relativePath)

      try {
        writeInstructionFile(fullPath, content)
        filesWritten.push(relativePath)
        log(`[sync] Wrote ${relativePath}`)
      } catch (writeError) {
        log(`[sync] Failed to write ${relativePath}: ${writeError}`)
      }
    }

    // Count total instruction files that had content
    const instructionCount = instructions.reduce(
      (count, set) =>
        count + set.files.filter((f) => typeof f.content === 'string' && f.content.trim()).length,
      0
    )

    log(`[sync] Successfully synced ${instructionCount} instruction file(s) to ${filesWritten.length} target(s)`)

    return {
      success: true,
      projectId,
      projectName,
      filesWritten,
      instructionCount,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error'
    log(`[sync] Failed to sync instructions: ${message}`)
    return {
      success: false,
      projectId,
      projectName: null,
      filesWritten: [],
      instructionCount: 0,
      error: message,
    }
  }
}

/**
 * Cleans up generated instruction files from the workspace.
 */
export async function cleanupInstructionFiles(options: Pick<SyncOptions, 'targets' | 'workspaceRoot' | 'verbose'> = {}): Promise<string[]> {
  const {
    targets = ['cursor', 'claudeCode', 'codex', 'antigravity', 'vscode'],
    workspaceRoot = process.cwd(),
    verbose = true,
  } = options

  const log = verbose ? console.error.bind(console) : () => {}
  const filesDeleted: string[] = []

  for (const target of targets) {
    const relativePath = IDE_TARGETS[target]
    const fullPath = path.join(workspaceRoot, relativePath)

    if (fs.existsSync(fullPath)) {
      try {
        // Only delete if it's a generated file
        const content = fs.readFileSync(fullPath, 'utf-8')
        if (content.includes('AUTO-GENERATED BY PINK SUNDEW MCP')) {
          fs.unlinkSync(fullPath)
          filesDeleted.push(relativePath)
          log(`[sync] Deleted ${relativePath}`)
        } else {
          log(`[sync] Skipped ${relativePath} (not auto-generated)`)
        }
      } catch (err) {
        log(`[sync] Failed to delete ${relativePath}: ${err}`)
      }
    }
  }

  return filesDeleted
}
