/**
 * Pink Sundew MCP Server - Global Instruction Sync
 *
 * Synchronizes agent instructions from the cloud API to a single local workspace file.
 * The target file is determined by AGENTPLANNER_CLIENT_ENV:
 * - cursor -> .cursorrules
 * - claude -> CLAUDE.md
 * - windsurf -> .windsurfrules
 * - vscode -> .github/copilot-instructions.md
 * - codex -> AGENTS.md
 * - default -> .agentrules
 *
 * Uses non-destructive "Injection Block" pattern with HTML comment markers.
 * User-defined content outside the sync block is preserved.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { getProjectId, isProjectScopingEnabled, getClientEnv } from './project-scope.js'
import { getProjectAgentControls, getInstructionFilesForProject } from './resources.js'
import { bridgeFetch } from './supabase.js'
import type { AgentInstructionSet } from './types.js'

/**
 * Sync boundary markers for non-destructive injection.
 * Content between these markers is managed by Pink Sundew.
 * User content outside these markers is preserved.
 */
const SYNC_START = '<!-- BEGIN:pinksundew-sync -->'
const SYNC_END = '<!-- END:pinksundew-sync -->'

/**
 * Regex to match the sync block including varying whitespace.
 * Captures everything between (and including) the markers.
 */
const SYNC_BLOCK_REGEX = new RegExp(
  `${escapeRegex(SYNC_START)}[\\s\\S]*?${escapeRegex(SYNC_END)}`,
  'g'
)

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Maps client environment to output file path.
 */
const CLIENT_ENV_FILES: Record<string, string> = {
  cursor: '.cursorrules',
  claude: 'CLAUDE.md',
  windsurf: '.windsurfrules',
  vscode: '.github/copilot-instructions.md',
  codex: 'AGENTS.md',
  antigravity: 'antigravity.md',
}

const DEFAULT_OUTPUT_FILE = '.agentrules'

export type SyncOptions = {
  /** Workspace root directory. Defaults to process.cwd(). */
  workspaceRoot?: string
  /** Whether to log sync activity. Defaults to true. */
  verbose?: boolean
}

export type SyncResult = {
  success: boolean
  projectId: string | null
  projectName: string | null
  clientEnv: string | null
  fileWritten: string | null
  instructionCount: number
  error?: string
}

/**
 * Gets the output file path based on client environment.
 */
function getOutputFilePath(clientEnv: string | null): string {
  if (clientEnv && clientEnv in CLIENT_ENV_FILES) {
    return CLIENT_ENV_FILES[clientEnv]
  }
  return DEFAULT_OUTPUT_FILE
}

/**
 * Fetches the active global instruction sets for a project.
 */
async function fetchActiveInstructions(projectId: string, envName?: string): Promise<{
  projectName: string
  instructions: AgentInstructionSet[]
}> {
  // Get agent controls to find active instruction set IDs
  const controls = await getProjectAgentControls(projectId)
  
  // Fetch the board state which includes instructions
  const boardState = await bridgeFetch<{
    project: { id: string; name: string } | null
    instructions: AgentInstructionSet[]
  }>(`/board/${projectId}`)

  // Filter to only global scope instructions that are active
  const activeInstructions = (boardState.instructions || []).filter(
    (instruction) => instruction.scope === 'global' && instruction.is_active !== false
  )

  // Fetch full content for each instruction set's files
  const allFileIds = activeInstructions.flatMap((set) =>
    set.files
      .filter((file) => file.file_name.toLowerCase().endsWith('.md'))
      .map((file) => file.id)
  )

  if (allFileIds.length > 0) {
    const filesWithContent = await getInstructionFilesForProject(projectId, allFileIds, envName)
    const contentMap = new Map(filesWithContent.map((f) => [f.id, f.content]))

    // Merge content into instruction sets
    for (const instruction of activeInstructions) {
      for (const file of instruction.files) {
        const content = contentMap.get(file.id)
        if (content !== undefined) {
          file.content = content
        }
      }
    }
  }

  return {
    projectName: boardState.project?.name ?? 'Unknown Project',
    instructions: activeInstructions,
  }
}

/**
 * Concatenates all instruction content into a single formatted string.
 * Files are separated with \n\n---\n\n as per the concatenation pattern.
 * Content is wrapped in sync markers for non-destructive injection.
 */
function buildSyncBlock(
  instructions: AgentInstructionSet[],
  projectName: string
): string {
  const contentBlocks: string[] = []

  for (const instruction of instructions) {
    // Sort files by name for consistent ordering
    const sortedFiles = [...instruction.files].sort((a, b) =>
      a.file_name.localeCompare(b.file_name)
    )

    for (const file of sortedFiles) {
      if (typeof file.content !== 'string' || !file.content.trim()) {
        continue
      }
      contentBlocks.push(file.content.trim())
    }
  }

  const timestamp = new Date().toISOString()
  const header = `// AUTO-GENERATED BY PINK SUNDEW - DO NOT EDIT THIS BLOCK\n// Last synced: ${timestamp}\n// Project: ${projectName}`

  let innerContent: string
  if (contentBlocks.length === 0) {
    innerContent = '<!-- No active global instructions configured -->'
  } else {
    // Concatenate with separator pattern
    innerContent = contentBlocks.join('\n\n---\n\n')
  }

  // Wrap in sync markers
  return `${SYNC_START}\n${header}\n\n${innerContent}\n${SYNC_END}`
}

/**
 * Writes content to a file using non-destructive injection pattern.
 * - If file doesn't exist: creates new file with the sync block
 * - If file exists with sync block: replaces only the sync block
 * - If file exists without sync block: appends sync block to end
 */
function writeInstructionFile(filePath: string, syncBlock: string): void {
  const dir = path.dirname(filePath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  if (!fs.existsSync(filePath)) {
    // File doesn't exist - create new file with sync block
    fs.writeFileSync(filePath, syncBlock + '\n', 'utf-8')
    return
  }

  // File exists - read current content
  const existingContent = fs.readFileSync(filePath, 'utf-8')

  let newContent: string
  if (SYNC_BLOCK_REGEX.test(existingContent)) {
    // Sync block exists - replace it
    // Reset regex lastIndex since we used test()
    SYNC_BLOCK_REGEX.lastIndex = 0
    newContent = existingContent.replace(SYNC_BLOCK_REGEX, syncBlock)
  } else {
    // No sync block - append to end with spacing
    const spacing = existingContent.endsWith('\n\n') ? '' : existingContent.endsWith('\n') ? '\n' : '\n\n'
    newContent = existingContent + spacing + syncBlock + '\n'
  }

  fs.writeFileSync(filePath, newContent, 'utf-8')
}

/**
 * Synchronizes global instructions from the cloud to a single local workspace file.
 * The target file is determined by AGENTPLANNER_CLIENT_ENV.
 */
export async function syncGlobalInstructions(options: SyncOptions = {}): Promise<SyncResult> {
  const {
    workspaceRoot = process.cwd(),
    verbose = true,
  } = options

  const log = verbose ? console.error.bind(console) : () => {}

  // Get the configured project ID
  if (!isProjectScopingEnabled()) {
    const error = 'No AGENTPLANNER_PROJECT_ID configured. Cannot sync instructions.'
    log(`[sync] ${error}`)
    return {
      success: false,
      projectId: null,
      projectName: null,
      clientEnv: null,
      fileWritten: null,
      instructionCount: 0,
      error,
    }
  }

  const projectId = getProjectId()!
  const clientEnv = getClientEnv()
  const outputFile = getOutputFilePath(clientEnv)
  
  log(`[sync] Syncing global instructions for project: ${projectId}`)
  if (clientEnv) {
    log(`[sync] Client environment: ${clientEnv} -> ${outputFile}`)
  } else {
    log(`[sync] No client environment specified, using default: ${outputFile}`)
  }

  try {
    // Fetch active instructions from the API
    const { projectName, instructions } = await fetchActiveInstructions(projectId, clientEnv ?? undefined)
    log(`[sync] Found ${instructions.length} active global instruction set(s) for "${projectName}"`)

    // Build sync block with markers
    const syncBlock = buildSyncBlock(instructions, projectName)

    // Write to the target file (non-destructive)
    const fullPath = path.join(workspaceRoot, outputFile)

    try {
      writeInstructionFile(fullPath, syncBlock)
      log(`[sync] Wrote ${outputFile}`)
    } catch (writeError) {
      const message = writeError instanceof Error ? writeError.message : 'Unknown error'
      log(`[sync] Failed to write ${outputFile}: ${message}`)
      return {
        success: false,
        projectId,
        projectName,
        clientEnv,
        fileWritten: null,
        instructionCount: 0,
        error: `Failed to write ${outputFile}: ${message}`,
      }
    }

    // Count total instruction files that had content
    const instructionCount = instructions.reduce(
      (count, set) =>
        count + set.files.filter((f) => typeof f.content === 'string' && f.content.trim()).length,
      0
    )

    log(`[sync] Successfully synced ${instructionCount} instruction file(s) to ${outputFile}`)

    return {
      success: true,
      projectId,
      projectName,
      clientEnv,
      fileWritten: outputFile,
      instructionCount,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error'
    log(`[sync] Failed to sync instructions: ${message}`)
    return {
      success: false,
      projectId,
      projectName: null,
      clientEnv,
      fileWritten: null,
      instructionCount: 0,
      error: message,
    }
  }
}

/**
 * Removes Pink Sundew sync blocks from instruction files.
 * Only removes the sync block content, preserving user-defined instructions.
 * If a file becomes empty after removal, deletes the file entirely.
 */
export async function cleanupInstructionFiles(options: Pick<SyncOptions, 'workspaceRoot' | 'verbose'> = {}): Promise<string[]> {
  const {
    workspaceRoot = process.cwd(),
    verbose = true,
  } = options

  const log = verbose ? console.error.bind(console) : () => {}
  const filesCleaned: string[] = []
  
  // Check all possible output files
  const allFiles = [...Object.values(CLIENT_ENV_FILES), DEFAULT_OUTPUT_FILE]

  for (const relativePath of allFiles) {
    const fullPath = path.join(workspaceRoot, relativePath)

    if (!fs.existsSync(fullPath)) {
      continue
    }

    try {
      const content = fs.readFileSync(fullPath, 'utf-8')
      
      // Check if sync block exists
      if (!SYNC_BLOCK_REGEX.test(content)) {
        log(`[sync] Skipped ${relativePath} (no sync block found)`)
        continue
      }

      // Reset regex lastIndex
      SYNC_BLOCK_REGEX.lastIndex = 0

      // Remove the sync block
      const cleanedContent = content.replace(SYNC_BLOCK_REGEX, '').trim()

      if (cleanedContent.length === 0) {
        // File is now empty - delete it
        fs.unlinkSync(fullPath)
        filesCleaned.push(relativePath)
        log(`[sync] Deleted ${relativePath} (was only sync block)`)
      } else {
        // File has other content - preserve it
        fs.writeFileSync(fullPath, cleanedContent + '\n', 'utf-8')
        filesCleaned.push(relativePath)
        log(`[sync] Removed sync block from ${relativePath}`)
      }
    } catch (err) {
      log(`[sync] Failed to clean ${relativePath}: ${err}`)
    }
  }

  return filesCleaned
}

// ============================================================================
// Background Polling Support
// ============================================================================

const HASH_FILE = '.pinksundew-hash'

/**
 * In-memory hash cache for fast comparisons.
 * Falls back to .pinksundew-hash file if memory is cleared.
 */
let inMemoryHash: string | null = null

/**
 * Reads the current local hash from memory or file.
 */
export function readLocalHash(workspaceRoot = process.cwd()): string | null {
  // Check memory first
  if (inMemoryHash !== null) {
    return inMemoryHash
  }

  // Fall back to file
  const hashPath = path.join(workspaceRoot, HASH_FILE)
  try {
    if (fs.existsSync(hashPath)) {
      const content = fs.readFileSync(hashPath, 'utf-8').trim()
      inMemoryHash = content
      return content
    }
  } catch {
    // Ignore read errors
  }

  return null
}

/**
 * Saves the hash to memory and file.
 */
export function saveLocalHash(hash: string, workspaceRoot = process.cwd()): void {
  inMemoryHash = hash

  const hashPath = path.join(workspaceRoot, HASH_FILE)
  try {
    fs.writeFileSync(hashPath, hash, 'utf-8')
  } catch {
    // Ignore write errors - in-memory cache is primary
  }
}

/**
 * Fetches the current cloud hash for a project's global instructions.
 * Returns null on error.
 */
export async function fetchCloudHash(projectId: string): Promise<string | null> {
  try {
    const response = await bridgeFetch<{ hash: string }>(`/instructions/hash/${projectId}`)
    return response.hash ?? null
  } catch (error) {
    console.error('[sync] Failed to fetch cloud hash:', error)
    return null
  }
}

/**
 * Interval ID for the background sync timer.
 * Exported for testing/cleanup purposes.
 */
let backgroundSyncInterval: ReturnType<typeof setInterval> | null = null

/**
 * Starts background polling for instruction changes.
 * Polls every `intervalMs` milliseconds (default: 2 minutes).
 * Silently syncs instructions when a hash change is detected.
 */
export function startBackgroundSync(options: {
  projectId: string
  workspaceRoot?: string
  intervalMs?: number
  verbose?: boolean
} = { projectId: '' }): void {
  const {
    projectId,
    workspaceRoot = process.cwd(),
    intervalMs = 60000, // 1 minute default
    verbose = true,
  } = options

  if (!projectId) {
    console.error('[sync] Cannot start background sync: no projectId provided')
    return
  }

  const log = verbose ? console.error.bind(console) : () => {}

  // Clear any existing interval
  if (backgroundSyncInterval) {
    clearInterval(backgroundSyncInterval)
  }

  log(`[sync] Starting background sync for project ${projectId} (every ${intervalMs / 1000}s)`)

  backgroundSyncInterval = setInterval(async () => {
    try {
      const currentLocalHash = readLocalHash(workspaceRoot)
      const cloudHash = await fetchCloudHash(projectId)

      if (cloudHash === null) {
        // Fetch failed, skip this cycle
        return
      }

      if (currentLocalHash !== cloudHash) {
        log('[sync] Hash mismatch detected, syncing...')
        const result = await syncGlobalInstructions({ workspaceRoot, verbose })
        
        if (result.success) {
          saveLocalHash(cloudHash, workspaceRoot)
          log(`[sync] Background sync complete: ${result.instructionCount} instruction(s)`)
        } else {
          log(`[sync] Background sync failed: ${result.error}`)
        }
      }
    } catch (error) {
      console.error('[sync] Background sync error:', error)
    }
  }, intervalMs)
}

/**
 * Stops the background sync timer.
 */
export function stopBackgroundSync(): void {
  if (backgroundSyncInterval) {
    clearInterval(backgroundSyncInterval)
    backgroundSyncInterval = null
    console.error('[sync] Background sync stopped')
  }
}
