/**
 * MCP Server Types - Re-exports from schemas for backward compatibility.
 * All types are now derived from Zod schemas for runtime validation.
 */

export {
  // Enums
  type TaskStatus,
  type TaskPriority,
  type TaskSignal,
  type TaskStateMessageSignal,
  type ExportFormat,
  type InstructionSetScope,
  type CoreMcpToolName,
  // Type guards
  isTaskStatus,
  isTaskPriority,
  isTaskSignal,
  // Entity types
  type ToolToggleMap,
  type AgentControls,
  type Project,
  type Tag,
  type AgentInstructionFile,
  type AgentInstructionSet,
  type LinkedInstructionSetSummary,
  type ResolvedInstructionSet,
  type TaskPlan,
  type TaskTimelineEntry,
  type TaskTimeline,
  type TaskStateMessage,
  type Task,
  type BoardState,
  type AbyssState,
  type ExportInstruction,
  type ExportTasksResult,
  // Input types
  type CreateTaskInput,
  type UpdateTaskInput,
  type MoveTaskInput,
  type SetTaskSignalInput,
  type AddTaskMessageInput,
  type AddPlanInput,
  type CreateTagInput,
  type DeleteTagInput,
  type ExportTasksInput,
  type SyncInstructionsInput,
  // Schemas (for runtime validation)
  TaskStatusSchema,
  TaskPrioritySchema,
  TaskSignalSchema,
  TaskStateMessageSignalSchema,
  ExportFormatSchema,
  InstructionSetScopeSchema,
  CoreMcpToolNameSchema,
  ToolToggleMapSchema,
  AgentControlsSchema,
  ProjectSchema,
  TagSchema,
  AgentInstructionFileSchema,
  AgentInstructionSetSchema,
  LinkedInstructionSetSummarySchema,
  ResolvedInstructionSetSchema,
  TaskPlanSchema,
  TaskTimelineEntrySchema,
  TaskTimelineSchema,
  TaskStateMessageSchema,
  TaskSchema,
  BoardStateSchema,
  AbyssStateSchema,
  ExportInstructionSchema,
  ExportTasksResultSchema,
  CreateTaskInputSchema,
  UpdateTaskInputSchema,
  MoveTaskInputSchema,
  SetTaskSignalInputSchema,
  AddTaskMessageInputSchema,
  AddPlanInputSchema,
  CreateTagInputSchema,
  DeleteTagInputSchema,
  ExportTasksInputSchema,
  SyncInstructionsInputSchema,
} from './schemas.js'